version: '3.1'
services:
  ui:
    build: .
    environment:
      HABIT_HOST: http://localhost:9001/
      TRACKING_HOST: http://localhost:9002/
      REPORT_HOST: http://localhost:9003/
      OIDC_AUTH: enabled
      OIDC_AUTHORITY_HOST: http://localhost:8080/auth/realms/habitcentric/.well-known/openid-configuration
      OIDC_CLIENT_ID: ui
    depends_on:
      - keycloak
      - habit
      - track
      - report
    ports:
      - "9004:9004"
  keycloak:
    image: habitcentric/auth-keycloak
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_USER: keycloak
      KEYCLOAK_PASSWORD: keycloak
  habit:
    image: rodolpheche/wiremock:2.28.1-alpine
    volumes:
      - ./stubs/habit:/home/wiremock/
    ports:
      - "9001:9001"
    command: --port 9001
  track:
    image: rodolpheche/wiremock:2.28.1-alpine
    volumes:
      - ./stubs/track:/home/wiremock/mappings
    ports:
      - "9002:9002"
    command: --port 9002
  report:
    image: rodolpheche/wiremock:2.28.1-alpine
    volumes:
      - ./stubs/report:/home/wiremock/mappings
    ports:
      - "9003:9003"
    command: --port 9003
