version: '3.1'
services:
  keycloak:
    image: jboss/keycloak:16.1.0
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_USER: keycloak
      KEYCLOAK_PASSWORD: keycloak
      KEYCLOAK_IMPORT: /realm/realm.json
    volumes:
      - ../../infrastructure/keycloak/realm.json:/realm/realm.json
  habit:
    image: rodolpheche/wiremock:2.28.1-alpine
    volumes:
      - ./stubs/habit:/home/wiremock/
    ports:
      - "9001:9001"
    command: --port 9001
  track:
    image: rodolpheche/wiremock:2.28.1-alpine
    volumes:
      - ./stubs/track:/home/wiremock/mappings
    ports:
      - "9002:9002"
    command: --port 9002
  report:
    image: rodolpheche/wiremock:2.28.1-alpine
    volumes:
      - ./stubs/report:/home/wiremock/mappings
    ports:
      - "9003:9003"
    command: --port 9003
