apiVersion: v1
kind: ConfigMap
metadata:
  name: track-fault-service
  namespace: hc-track
data:
 nginx.conf: |-
    events {}
    http {
        server {
          listen 8080;
            location / {
              echo_sleep 2;
              echo Delayed response;
            }
        }
    }