apiVersion: v1
kind: ConfigMap
metadata:
  name: track-fault-service
  namespace: hc-track
data:
 nginx.conf: |-
    events {}
    http {
        server {
          listen 8080;
            location / {
                return 500;
            }
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: track-fault-service
  namespace: hc-track
  labels:
    app: track-fault-service
spec:
  selector:
    matchLabels:
      app: track-fault-service
  replicas: 1
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: track-fault-service
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-config
          configMap:
            name: track-fault-service
---
apiVersion: v1
kind: Service
metadata:
  name: track-fault-service
  namespace: hc-track
spec:
  ports:
  - name: service
    port: 8080
  selector:
    app: track-fault-service