test report:
  only:
    changes:
      - report/**/*
  stage: test
  image: openjdk:11.0.4-jdk-slim-buster@sha256:aa55d9c3be02f2710d5fb5fef87d5c07c9f7ad2c481105a891a4bdd485b2e2bd
  before_script:
    - cd report
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script: ./gradlew --build-cache check
  cache:
    key: "${CI_COMMIT_REF_NAME}_report"
    policy: push
    paths:
      - report/build
      - report/.gradle
  artifacts:
    when: always
    name: "${CI_BUILD_STAGE}_report_${CI_BUILD_REF_NAME}"
    expire_in: 1 week
    paths:
      - report/build/reports/tests/
      - report/build/test-results/test/TEST-*.xml
    reports:
      junit: report/build/test-results/*/TEST-*.xml

build report:
  only:
    changes:
      - report/**/*
  needs:
    - test report
  stage: build
  image: openjdk:11.0.7-jdk-slim-buster@sha256:663ad452a41122c79eb294198ad6336240c4c65b663acd91aa64c0431eaa1db5
  before_script:
    - cd report
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script: ./gradlew --build-cache build
  cache:
    key: "${CI_COMMIT_REF_NAME}_report"
    policy: pull
    paths:
      - report/build
      - report/.gradle
  artifacts:
    when: always
    name: "${CI_BUILD_STAGE}_report_${CI_BUILD_REF_NAME}"
    expire_in: 1 week
    paths:
      - report/build/libs/report-*.jar

build report image:
  only:
    changes:
      - report/**/*
  needs:
    - build report
  stage: build image
  image: docker:19.03.1@sha256:5372cccaf84ae9a4d4f5c2b50ba7db6627cf3eff12785876f3354bbc2b0b57ea
  services:
    - docker:19.03.1-dind@sha256:ffa52c7b48390439f5858cadfaf8163c8cde2104873b3dc9850d8e021dbd3f24
  before_script:
    - cd report
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

publish report image:
  only:
    refs:
      - main
    changes:
      - report/**/*
  needs:
    - build report image
  variables:
    DOCKER_HUB_REGISTRY_IMAGE: $DOCKER_HUB_REGISTRY_ORG/report
  stage: publish image
  image: docker:19.03.1@sha256:5372cccaf84ae9a4d4f5c2b50ba7db6627cf3eff12785876f3354bbc2b0b57ea
  services:
    - docker:19.03.1-dind@sha256:ffa52c7b48390439f5858cadfaf8163c8cde2104873b3dc9850d8e021dbd3f24
  before_script:
    - cd report
  script:
    - docker login -u $DOCKER_HUB_REGISTRY_USER -p $DOCKER_HUB_REGISTRY_PASSWORD $DOCKER_HUB_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG $DOCKER_HUB_REGISTRY_IMAGE:latest
    - docker push $DOCKER_HUB_REGISTRY_IMAGE:latest
