test report:
  extends: .test
  variables:
    SERVICE_FOLDER: report
  only:
    changes:
      - report/**/*
  cache:
    paths:
      - report/build
      - report/.gradle
  artifacts:
    paths:
      - report/build/reports/tests/
      - report/build/test-results/test/TEST-*.xml
      - report/build/reports/jacoco/test/jacocoTestReport.xml
    reports:
      junit: report/build/test-results/*/TEST-*.xml

coverage report:
  extends: .convert-coverage
  variables:
    SERVICE_FOLDER: report
    MAIN_SRC: src/main/kotlin/
  only:
    changes:
      - report/**/*
  needs:
    - test report
  artifacts:
    reports:
      cobertura: report/build/cobertura.xml

build report:
  extends: .build
  variables:
    SERVICE_FOLDER: report
  only:
    changes:
      - report/**/*
  needs:
    - test report
  cache:
    paths:
      - report/build
      - report/.gradle
  artifacts:
    paths:
      - report/build/libs/report-*.jar

build report image:
  extends: .docker-build
  variables:
    IMAGE_NAME: report
    SERVICE_FOLDER: report
  only:
    changes:
      - report/**/*
  needs:
    - build report

publish report image:
  extends: .docker-publish
  only:
    changes:
      - report/**/*
  needs:
    - build report image
  variables:
    IMAGE_NAME: report
    DOCKER_HUB_REGISTRY_IMAGE: $DOCKER_HUB_REGISTRY_ORG/report
