version: '3.1'
services:
  db:
    image: bitnami/postgresql:15
    restart: always
    ports:
      - 10002:10002
    environment:
      POSTGRESQL_PASSWORD: postgres
      POSTGRESQL_PORT_NUMBER: 10002
