variables:
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "" # workaround for https://gitlab.com/gitlab-org/gitlab-runner/issues/4501

stages:
  - test
  - build
  - build image
  - publish image

include:
  - '/habit/.gitlab-ci.yml'
  - '/track/.gitlab-ci.yml'
  - '/report/.gitlab-ci.yml'
  - '/ui/.gitlab-ci.yml'
