version: '3'
services:
  habit:
    image: rodolpheche/wiremock:2.28.1-alpine
    volumes:
      - ./stubs/habit:/home/wiremock/mappings
    ports:
      - 9001:9001
    command: --global-response-templating --port 9001
  track:
    image: rodolpheche/wiremock:2.28.1-alpine
    volumes:
      - ./stubs/track:/home/wiremock/mappings
    ports:
      - 9002:9002
    command: --global-response-templating --port 9002
