apiVersion: v1
name: habit
version: 0.1.0
appVersion: latest
description: Chart for the habit service of habitcentric, a service to track habits
keywords:
  - habitcentric
  - habit
  - microservices
home: https://confluence.codecentric.de/display/HAB/habitcentric
sources:
  - https://gitlab.com/habitcentric/hc-habit
maintainers:
  - name: Michael Follmann
    email: michael.follmann@codecentric.de
    url: http://gitlab.com/michael.follmann
  - name: Dennis Effing
    email: dennis.effing@codecentric.de
    url: http://gitlab.com/denniseffing
engine: gotpl
