version: '3.1'
services:
  gateway:
    build: .
    environment:
      HABIT_URI: http://habit:8080
      TRACK_URI: http://track:8080
      UI_URI: http://ui
    ports:
      - 8419:8080
  habit:
    image: habitcentric/habit
    depends_on:
      - habit-db
    environment:
      DB_HOST: habit-db
  habit-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
  track:
    image: habitcentric/track
    depends_on:
      - track-db
    environment:
      DB_HOST: track-db
  track-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
  ui:
    image: habitcentric/ui
    environment:
      HABIT_SERVICE_HOST: http://localhost:8419/
      TRACKING_SERVICE_HOST: http://localhost:8419/
