spring:
  application:
    name: habit
  profiles:
    active: chaos-monkey
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:10001}/${DB_NAME:postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  jpa:
    database-platform: postgres
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: ${spring.liquibase.default-schema}
        dialect: org.hibernate.dialect.PostgreSQLDialect
        # https://github.com/spring-projects/spring-boot/issues/12007#issuecomment-370774241
        jdbc.lob.non_contextual_creation: true
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
    default-schema: hc_habit

  kafka:
    client-id: habit
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:11003}
    properties:
      "security.protocol": SASL_PLAINTEXT
      "sasl.mechanism": PLAIN
      "sasl.jaas.config": 'org.apache.kafka.common.security.plain.PlainLoginModule required username="${KAFKA_USER:habit}" password="${KAFKA_PASSWORD:habit}";'
    producer:
      properties:
        "spring.json.type.mapping": "habit-created:de.codecentric.hc.habit.habits.Habit.HabitCreated,habit-deleted:de.codecentric.hc.habit.habits.Habit.HabitDeleted"
logging:
  level:
    liquibase.executor: WARN
server:
  port: 9001
  error:
    # some integration tests rely on the error details
    include-message: always
    include-binding-errors: always

springdoc:
  packages-to-scan: de.codecentric.hc.habit
  paths-to-match: /habits/**
  enable-spring-security: false
