spring:
  application:
    name: habit
  profiles:
    active: chaos-monkey
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:10001}/${DB_NAME:postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  jpa:
    database-platform: postgres
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: ${spring.liquibase.defaultSchema}
        dialect: org.hibernate.dialect.PostgreSQLDialect
        # https://github.com/spring-projects/spring-boot/issues/12007#issuecomment-370774241
        jdbc.lob.non_contextual_creation: true
  liquibase.defaultSchema: hc_habit
logging:
  level:
    liquibase.executor: WARN
server:
  port: 9001
  error:
    # some integration tests rely on the error details
    include-message: always
    include-binding-errors: always
