apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "ui.fullname" . }}
  labels:
    app: {{ template "ui.name" . }}
    chart: {{ template "ui.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: {{ .Values.updateStrategyType }}
  selector:
    matchLabels:
  {{- include "ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "ui.labels" . | nindent 8 }}
      {{- with .Values.podLabels -}}
      {{- toYaml . | nindent 8 }}
      {{- end -}}
      {{- with .Values.podAnnotations }}
      annotations:
    {{- toYaml . | nindent 8 }}
    {{- end }}
    spec:
      {{- if .Values.serviceAccount.enabled }}
      serviceAccountName: {{ default (include "ui.fullname" . ) .Values.serviceAccount.name }}
      {{- end }}
      containers:
        - name: {{ template "ui.fullname" . }}
          image: {{ template "ui.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http-ui
              containerPort: 80
          env:
            {{- if .Values.oidc.enabled }}
            - name: OIDC_AUTH
              value: enabled
            - name: OIDC_AUTHORITY_HOST
              value: {{ .Values.oidc.authorityUri }}
            - name: OIDC_CLIENT_ID
              value: {{ .Values.oidc.clientId }}
          {{- end }}
          readinessProbe:
            httpGet:
              path: /ui
              port: http-ui
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
          livenessProbe:
            httpGet:
              path: /ui
              port: {{ .Values.service.port }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
