stable:
  # appVersionOverride:
  report:
    habitServiceUrl: http://habit.hc-habit:9001
    trackServiceUrl: http://track.hc-track:9002
    enableMonthlyRate: false

  image:
    registry: docker.io
    repository: habitcentric/report
    tag: latest
    pullPolicy: Always

  ## Configure extra environment variables for the container
  extraEnv: [ ]

  ## Number of service instances
  replicas: 1

canary:
  enabled: false
  # appVersionOverride:
  report:
    habitServiceUrl: http://habit.hc-habit:9001
    trackServiceUrl: http://track.hc-track:9002
    enableMonthlyRate: true

  image:
    registry: docker.io
    repository: habitcentric/report
    tag: latest
    pullPolicy: Always

  ## Configure extra environment variables for the container
  extraEnv: [ ]

  ## Number of service instances
  replicas: 1

## habitcentric report service configuration
service:
  ## Additional service annotations which may be required
  annotations: {}

  ## ServiceType
  ## ref: https://kubernetes.io/docs/user-guide/services/#publishing-services---service-types
  type: ClusterIP

  ## Internal service port
  port: 9003

  ## nodePort value for the LoadBalancer and NodePort service types
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport
  # nodePort:

## Pod Service Account
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
serviceAccount:
  enabled: false

  ## Name of an already existing service account. Setting this value disables the automatic service account creation.
  # name:

## Configure extra options for liveness and readiness probes
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#configure-probes)
readinessProbe:
  enabled: true
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

livenessProbe:
  enabled: true
  initialDelaySeconds: 40
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1


## Additional pod labels which may be required
podLabels: {}

## Additional pod annotations which may be required
podAnnotations:
  test: test

## updateStrategy for habitcentric habit Deployment
## ref: https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#update-strategies
updateStrategyType: RollingUpdate
