{{- if and (.Values.serviceAccount.enabled) (not .Values.serviceAccount.name) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
  {{- include "habit.labels" . | nindent 4 }}
  name: {{ template "habit.fullname" . }}
  {{- end }}
