apiVersion: v1
name: gateway
version: 1.0.0
appVersion: v1
description: Chart for the gateway service of habitcentric, habitcentric's API gateway
keywords:
  - habitcentric
  - gateway
  - microservices
home: https://confluence.codecentric.de/display/HAB/habitcentric
sources:
  - https://gitlab.com/habitcentric/habitcentric
maintainers:
  - name: Michael Follmann
    email: michael.follmann@codecentric.de
    url: http://gitlab.com/michael.follmann
  - name: Dennis Effing
    email: dennis.effing@codecentric.de
    url: http://gitlab.com/denniseffing
engine: gotpl
