apiVersion: v1
kind: Service
metadata:
  name: {{ template "report.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "report.name" . }}
    app.kubernetes.io/component: report
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ template "report.chart" . }}
    helm.sh/release: {{ .Release.Name }}
  {{- with .Values.service.annotations }}
  annotations:
  {{ toYaml . | indent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http-report
      port: {{ .Values.service.port }}
      targetPort: http-report
  selector:
    app.kubernetes.io/name: {{ template "report.name" . }}
    app.kubernetes.io/component: report
    app.kubernetes.io/instance: {{ .Release.Name }}
