{{- if and (.Values.serviceAccount.enabled) (not .Values.serviceAccount.name) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: {{ template "report.name" . }}
    app.kubernetes.io/component: report
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ template "report.chart" . }}
    helm.sh/release: {{ .Release.Name }}
  name: {{ template "report.fullname" . }}
  {{- end }}
