{{- if and (.Values.serviceAccount.enabled) (not .Values.serviceAccount.name) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
  {{- include "ui.labels" . | nindent 4 }}
  name: {{ template "ui.fullname" . }}
  {{- end }}
