test gateway:
  extends: .test
  variables:
    SERVICE_FOLDER: gateway
  only:
    changes:
      - services/gateway/**/*
  cache:
    paths:
      - services/gateway/build
      - services/gateway/.gradle
  artifacts:
    paths:
      - services/gateway/build/reports/tests/
      - services/gateway/build/test-results/test/TEST-*.xml
      - services/gateway/build/reports/jacoco/test/jacocoTestReport.xml
    reports:
      junit: services/gateway/build/test-results/*/TEST-*.xml

coverage gateway:
  extends: .convert-coverage
  variables:
    SERVICE_FOLDER: gateway
  only:
    changes:
      - services/gateway/**/*
  needs:
    - test gateway
  artifacts:
    reports:
      cobertura: services/gateway/build/cobertura.xml

build gateway:
  extends: .build
  variables:
    SERVICE_FOLDER: gateway
  only:
    changes:
      - services/gateway/**/*
  needs:
    - test gateway
  cache:
    paths:
      - services/gateway/build
      - services/gateway/.gradle
  artifacts:
    paths:
      - services/gateway/build/libs/hc-gateway-*.jar

build gateway image:
  extends: .docker-build
  variables:
    SERVICE_FOLDER: gateway
    IMAGE_NAME: gateway
  only:
    changes:
      - services/gateway/**/*
  needs:
    - build gateway

publish gateway image:
  extends: .docker-publish
  only:
    changes:
      - services/gateway/**/*
  needs:
    - build gateway image
  variables:
    IMAGE_NAME: gateway
    DOCKER_HUB_REGISTRY_IMAGE: $DOCKER_HUB_REGISTRY_ORG/gateway
