version: '3.1'
services:
  auth-keycloak:
    image: habitcentric/auth-keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: postgres
      DB_ADDR: auth-keycloak-db
      DB_PORT: 10003
      DB_USER: keycloak
      DB_PASSWORD: password
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - auth-keycloak-db
    ports:
      - 8080:8080
    networks:
      habitcentric-net:
        aliases:
          - habitcentric.demo
  auth-keycloak-db:
    image: bitnami/postgresql:13
    environment:
      POSTGRESQL_USER: keycloak
      POSTGRESQL_PASSWORD: password
      POSTGRESQL_PORT_NUMBER: 10003
      POSTGRESQL_DATABASE: keycloak
    volumes:
      - auth-keycloak-db-data:/var/lib/postgresql/data
    networks:
      - habitcentric-net
  gateway:
    build: .
    environment:
      AUTH_TYPE: OAUTH_2_LOGIN
      AUTH_URI: http://habitcentric.demo:8080
      HABIT_URI: http://habit:9001
      TRACK_URI: http://track:9002
      REPORT_URI: http://report:9003
      UI_URI: http://ui:9004
    ports:
      - 9000:9000
    networks:
      - habitcentric-net
  habit:
    image: habitcentric/habit
    depends_on:
      - habit-db
    environment:
      DB_HOST: habit-db
    networks:
      - habitcentric-net
  habit-db:
    image: bitnami/postgresql:13
    restart: always
    environment:
      POSTGRESQL_PASSWORD: postgres
      POSTGRESQL_PORT_NUMBER: 10001
    networks:
      - habitcentric-net
  track:
    image: habitcentric/track
    depends_on:
      - track-db
    environment:
      DB_HOST: track-db
    networks:
      - habitcentric-net
  track-db:
    image: bitnami/postgresql:13
    restart: always
    environment:
      POSTGRESQL_PASSWORD: postgres
      POSTGRESQL_PORT_NUMBER: 10002
    networks:
      - habitcentric-net
  report:
    image: habitcentric/report
    environment:
      HABIT_SERVICE_URL: http://habit:9001
      TRACK_SERVICE_URL: http://track:9002
    networks:
      - habitcentric-net
  ui:
    image: habitcentric/ui
    environment:
      HABIT_SERVICE_HOST: http://localhost:9000/
      TRACKING_SERVICE_HOST: http://localhost:9000/
    networks:
      - habitcentric-net
volumes:
  auth-keycloak-db-data:
networks:
  habitcentric-net:
