spring:
  application:
    name: hc-gateway
gateway:
  target:
    uri:
      habit: ${HABIT_URI:http://localhost:8180}
      track: ${TRACK_URI:http://localhost:8219}
      ui: ${UI_URI:http://localhost:8171}

---

spring:
  profiles: local
server:
  port: 8431
  error:
    include-stacktrace: ALWAYS
