repositories:
  - name: kiali
    url: https://kiali.org/helm-charts

releases:
  - name: kiali-operator
    namespace: kiali-operator
    chart: kiali/kiali-operator
    values:
      - ./values/kiali-operator.values.yaml
