bases:
  - environments.yaml

repositories:
  - name: istio
    url: https://istio-release.storage.googleapis.com/charts

releases:
  - name: istio-cni
    namespace: kube-system
    chart: istio/cni
    version: 1.15.0
    installed: {{ eq .Environment.Name "cni" | toYaml }}
