environments:
  default:
  cni:

repositories:
  - name: istio
    url: https://istio-release.storage.googleapis.com/charts

releases:
  - name: istio-cni
    namespace: kube-system
    chart: istio/cni
    installed: {{ eq .Environment.Name "cni" | toYaml }}
