repositories:
  - name: incubator
    url: https://charts.helm.sh/incubator

releases:
  - name: istio-control-plane
    namespace: istio-system
    chart: incubator/raw
    values:
      - resources:
        - apiVersion: install.istio.io/v1alpha1
          kind: IstioOperator
          metadata:
            name: istio-deployment
          spec:
            profile: demo
            namespace: istio-system
            tag: 1.8.1

            values:
              global:
                tracer:
                  zipkin:
                    address: jaeger-collector.istio-system.svc.cluster.local:9411

              meshConfig:
                enablePrometheusMerge: true
                enableTracing: true
                defaultConfig:
                  tracing:
                    sampling: 100