bases:
  - environments.yaml

repositories:
  - name: istio
    url: https://istio-release.storage.googleapis.com/charts

releases:
  - name: istiod
    namespace: istio-system
    chart: istio/istiod
    version: 1.28.2
    wait: true
    values:
      - ./values/istiod.values.yaml.gotmpl
