repositories:
  - name: incubator
    url: https://charts.helm.sh/incubator

releases:
  - name: istio-control-plane
    namespace: istio-system
    chart: incubator/raw
    values:
      - resources:
        - apiVersion: install.istio.io/v1alpha1
          kind: IstioOperator
          metadata:
            name: istio-deployment
          spec:
            profile: demo
            namespace: istio-system
            tag: 1.6.2

            addonComponents:
              prometheus:
                enabled: false
              kiali:
                enabled: false
              grafana:
                enabled: false
              tracing:
                enabled: false


            values:
              meshConfig:
                enablePrometheusMerge: true

              pilot:
                deploymentLabels:
                  app.kubernetes.io/name: istiod

              tracing:
                enabled: false

              kiali:
                enabled: false