repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: incubator
    url: https://charts.helm.sh/incubator

releases:
  - name: prometheus
    namespace: istio-system
    chart: prometheus-community/prometheus
    values:
      - ./values/prometheus.values.yaml
  - name: kiali
    namespace: istio-system
    chart: incubator/raw
    values:
      - ./values/kiali.values.yaml