repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: incubator
    url: https://charts.helm.sh/incubator
  - name: kiali
    url: https://kiali.org/helm-charts
  - name: jaegertracing
    url: https://jaegertracing.github.io/helm-charts
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  - name: prometheus
    namespace: istio-system
    chart: prometheus-community/prometheus
    values:
      - ./values/prometheus.values.yaml
  - name: kiali
    namespace: istio-system
    chart: kiali/kiali-server
    values:
      - ./values/kiali.values.yaml
  - name: jaeger
    namespace: istio-system
    chart: jaegertracing/jaeger
    values:
      - ./values/jaeger.values.yaml
  - name: grafana
    namespace: istio-system
    chart: grafana/grafana
    values:
      - ./values/grafana.values.yaml
