repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:
  - name: prometheus
    namespace: istio-system
    chart: prometheus-community/prometheus
    values:
      - ./values/prometheus.values.yaml