habit:
  service-url: http://localhost:9001

track:
  service-url: http://localhost:9002

report:
  enable-monthly-rate: false

spring:
  application:
    name: report
  profiles:
    active: chaos-monkey
  jackson:
    default-property-inclusion: NON_NULL
server:
  port: 9003

management:
  tracing:
    baggage:
      remote-fields: authorization
    sampling:
      probability: 1.0
