habit:
  service-url: http://localhost:9001

track:
  service-url: http://localhost:9002

report:
  enable-monthly-rate: false

spring:
  application:
    name: report
  profiles:
    active: chaos-monkey
  sleuth:
    baggage:
      remote-fields: authorization
  jackson:
    default-property-inclusion: NON_NULL
server:
  port: 9003
