apiVersion: v1
kind: Service
metadata:
  namespace: habitcentric
  name: ui
spec:
  ports:
    - name: http-hcui
      port: 80
      targetPort: 80
  selector:
    app: habitcentric
    component: ui