environments:
  default:
  istio:
  linkerd:
  kuma:
  traefik-mesh:

releases:
  - name: ui
    namespace: hc-ui
    labels:
      service: ui
    chart: ../../../services/ui/helm/ui
    values:
      - ./values/ui-values.yaml.gotmpl
  - name: habit
    namespace: hc-habit
    labels:
      service: habit
    chart: ../../../services/habit/helm/habit
    values:
      - ./values/habit-values.yaml.gotmpl
  - name: track
    namespace: hc-track
    labels:
      service: track
    chart: ./../../services/track/helm/track
    values:
      - ./values/track-values.yaml.gotmpl
  - name: report
    namespace: hc-report
    labels:
      service: report
    chart: ../../../services/report/helm/report
    values:
      - ./values/report-values.yaml.gotmpl
  {{- if eq .Environment.Name "default" }}
  - name: gateway
    namespace: hc-gateway
    labels:
      service: gateway
    chart: ../../../services/gateway/helm/gateway
    values:
      - ./values/gateway-values.yaml.gotmpl
  {{- end }}

