stages:
  - build image
  - publish image

variables:
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_DRIVER: overlay2
  DOCKER_HUB_REGISTRY_IMAGE: $DOCKER_HUB_REGISTRY_ORG/$CI_PROJECT_NAME
  DOCKER_TLS_CERTDIR: "" # workaround for https://gitlab.com/gitlab-org/gitlab-runner/issues/4501

services:
  - docker:19.03.1-dind@sha256:ffa52c7b48390439f5858cadfaf8163c8cde2104873b3dc9850d8e021dbd3f24

build image:
  stage: build image
  image: docker:19.03.1@sha256:5372cccaf84ae9a4d4f5c2b50ba7db6627cf3eff12785876f3354bbc2b0b57ea
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

publish image:
  stage: publish image
  image: docker:19.03.1@sha256:5372cccaf84ae9a4d4f5c2b50ba7db6627cf3eff12785876f3354bbc2b0b57ea
  script:
    - docker login -u $DOCKER_HUB_REGISTRY_USER -p $DOCKER_HUB_REGISTRY_PASSWORD $DOCKER_HUB_REGISTRY
    - docker build -t $DOCKER_HUB_REGISTRY_IMAGE:latest -t $DOCKER_HUB_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker push $DOCKER_HUB_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $DOCKER_HUB_REGISTRY_IMAGE:latest
  only:
    - master
