version: '3.1'
services:
  keycloak:
    build: .
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: postgres
      DB_ADDR: keycloak-db
      DB_USER: keycloak
      DB_PASSWORD: password
    depends_on:
      - keycloak-db
  keycloak-db:
    image: postgres:9.6
    environment:
      PGDATA: /var/lib/postgresql/data/keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
volumes:
  keycloak-db-data: