version: '3.1'
services:
  keycloak:
    build: .
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: postgres
      DB_ADDR: keycloak-db
      DB_PORT: 10003
      DB_USER: keycloak
      DB_PASSWORD: password
    depends_on:
      - keycloak-db
  keycloak-db:
    image: bitnami/postgresql:13
    environment:
      POSTGRESQL_USER: keycloak
      POSTGRESQL_PASSWORD: password
      POSTGRESQL_PORT_NUMBER: 10003
      POSTGRESQL_DATABASE: keycloak
    ports:
      - 10003
    volumes:
      - keycloak-db-data:/bitnami/postgresql
volumes:
  keycloak-db-data:
