version: '3.1'
services:
  keycloak:
    image: jboss/keycloak:latest
    ports:
      - 8080:8080
    environment: 
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_USER: keycloak
      DB_PASSWORD: password
    depends_on: 
      - postgres
  postgres:
    image: postgres
    volumes: 
      - postgres-data:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data/keycloak
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
volumes:
  postgres-data: