stages:
  - build
  - build image
  - publish image

services:
  - docker:dind

variables:
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_DRIVER: overlay2
  DOCKER_HUB_REGISTRY_IMAGE: $DOCKER_HUB_REGISTRY_ORG/track

build:
  stage: build
  image: gradle:4.10.2-jdk8-alpine
  script: "gradle clean build"
  artifacts:
    when: always
    name: "${CI_BUILD_STAGE}_${CI_BUILD_REF_NAME}"
    expire_in: 1 week
    paths:
      - build/libs/hc-track-*.jar
      - build/reports/tests/test/
      - build/test-results/test/TEST-*.xml

build image:
  stage: build image
  image: docker:stable
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

publish image:
  stage: publish image
  image: docker:stable
  script:
    - docker login -u $DOCKER_HUB_REGISTRY_USER -p $DOCKER_HUB_REGISTRY_PASSWORD $DOCKER_HUB_REGISTRY
    - docker build -t $DOCKER_HUB_REGISTRY_IMAGE:latest .
    - docker push $DOCKER_HUB_REGISTRY_IMAGE:latest
  only:
    - master
