version: '3.1'
services:
  app:
    build: .
    environment:
      DB_HOST: db
    ports:
      - 8219:8080
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
