apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: keycloak-mtls-disabled
  namespace: hc-keycloak
spec:
  mtls:
    mode: PERMISSIVE
---
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: hc-habit-oidc-jwt
  namespace: hc-habit
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: habit
      app.kubernetes.io/instance: habit
  jwtRules:
  - issuer: https://habitcentric.demo/auth/realms/habitcentric
    jwksUri: http://keycloak-http.hc-keycloak.svc.cluster.local:8080/auth/realms/habitcentric/protocol/openid-connect/certs
    forwardOriginalToken: true
  - issuer: http://habitcentric.demo/auth/realms/habitcentric
    jwksUri: http://keycloak-http.hc-keycloak.svc.cluster.local:8080/auth/realms/habitcentric/protocol/openid-connect/certs
    forwardOriginalToken: true
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: hc-habit-oidc-policy
  namespace: hc-habit
spec:
  action: ALLOW
  selector:
    matchLabels:
      app.kubernetes.io/name: habit
      app.kubernetes.io/instance: habit
  rules:
  - from:
    - source:
        requestPrincipals: ["*"]
---
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: hc-track-oidc-jwt
  namespace: hc-track
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: track
      app.kubernetes.io/instance: track
  jwtRules:
  - issuer: https://habitcentric.demo/auth/realms/habitcentric
    jwksUri: http://keycloak-http.hc-keycloak.svc.cluster.local:8080/auth/realms/habitcentric/protocol/openid-connect/certs
    forwardOriginalToken: true
  - issuer: http://habitcentric.demo/auth/realms/habitcentric
    jwksUri: http://keycloak-http.hc-keycloak.svc.cluster.local:8080/auth/realms/habitcentric/protocol/openid-connect/certs
    forwardOriginalToken: true
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: hc-track-oidc-policy
  namespace: hc-track
spec:
  action: ALLOW
  selector:
    matchLabels:
      app.kubernetes.io/name: track
      app.kubernetes.io/instance: track
  rules:
  - from:
    - source:
        requestPrincipals: ["*"]
---
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: hc-report-oidc
  namespace: hc-report
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: report
      app.kubernetes.io/instance: report
  jwtRules:
  - issuer: https://habitcentric.demo/auth/realms/habitcentric
    jwksUri: http://keycloak-http.hc-keycloak.svc.cluster.local:8080/auth/realms/habitcentric/protocol/openid-connect/certs
    forwardOriginalToken: true
  - issuer: http://habitcentric.demo/auth/realms/habitcentric
    jwksUri: http://keycloak-http.hc-keycloak.svc.cluster.local:8080/auth/realms/habitcentric/protocol/openid-connect/certs
    forwardOriginalToken: true
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: hc-report-oidc-policy
  namespace: hc-report
spec:
  action: ALLOW
  selector:
    matchLabels:
      app.kubernetes.io/name: report
      app.kubernetes.io/instance: report
  rules:
  - from:
    - source:
        requestPrincipals: ["*"]
