image:
  registry: docker.io
  repository: habitcentric/ui
  tag: latest
  ## Specifies an imagePullPolicy
  ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
  ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  pullPolicy: Always

## habitcentric ui service configuration
service:
  ## Additional service annotations which may be required
  annotations: {}

  ## ServiceType
  ## ref: https://kubernetes.io/docs/user-guide/services/#publishing-services---service-types
  type: ClusterIP

  ## Internal service port
  port: 9004

  ## nodePort value for the LoadBalancer and NodePort service types
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport
  # nodePort:

## Pod Service Account
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
serviceAccount:
  enabled: false

  ## Name of an already existing service account. Setting this value disables the automatic service account creation.
  # name:

## Configure extra options for liveness and readiness probes
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#configure-probes)
readinessProbe:
  enabled: true
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

livenessProbe:
  enabled: true
  initialDelaySeconds: 40
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

## OpenID Connect configuration
oidc:
  enabled: true
  authorityUri: http://keycloak.demo/auth/realms/habitcentric/.well-known/openid-configuration
  clientId: habitcentric

## Number of service instances
replicas: 1

## Additional pod labels which may be required
podLabels: {}

## Additional pod annotations which may be required
podAnnotations: {}

## updateStrategyType for habitcentric ui Deployment
## ref: https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#update-strategies
updateStrategyType: RollingUpdate
