version: '3.1'
services:
  app:
    build: .
    environment:
      DB_HOST: db
    ports:
      - 9001:9001
    depends_on:
      - db
  db:
    image: bitnami/postgresql:13
    restart: always
    ports:
      - 10001:10001
    environment:
      POSTGRESQL_PASSWORD: postgres
      POSTGRESQL_PORT_NUMBER: 10001
