### Get all habits

GET http://localhost:9001/habits
X-User-Id: default

### Create new habit

POST http://localhost:9001/habits
X-User-Id: default
Content-Type: application/json

{
  "name": "Play guitar",
  "schedule": {
    "repetitions": 5,
    "frequency": "MONTHLY"
  }
}

### Delete habit
# Retrieve the ID by fetching the habits first
DELETE http://localhost:9001/habits/8ffa23a1-e91b-45a3-9060-3b0f53c0c6f3
X-User-Id: default
