{{- $ingress := .Values.ingress -}}
  {{- if $ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "gateway.fullname" . }}
  labels:
  {{- include "gateway.labels" . | nindent 4 }}
  {{- with $ingress.labels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $ingress.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if $ingress.tls }}
  tls:
    {{- range $ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
  {{- end }}
  rules:
    {{- range $ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingress.path }}
            backend:
              serviceName: {{ template "gateway.fullname" $ }}
              servicePort: http-gateway
          - path: {{ $ingress.path }}*
            backend:
              serviceName: {{ template "gateway.fullname" $ }}
              servicePort: http-gateway
  {{- end }}
  {{- end -}}
