apiVersion: v1
kind: Service
metadata:
  name: {{ template "habit.fullname" . }}
  labels:
  {{- include "habit.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http-habit
      port: {{ .Values.service.port }}
      targetPort: http-habit
  selector:
  {{- include "habit.selectorLabels" . | nindent 4 }}
