build auth-keycloak image:
  extends: .docker-build
  only:
    changes:
      - services/auth-keycloak/**/*
  variables:
    SERVICE_FOLDER: auth-keycloak
    IMAGE_NAME: auth-keycloak
  only:
    changes:
      - auth-keycloak/**/*

publish auth-keycloak image:
  extends: .docker-publish
  only:
    changes:
      - services/auth-keycloak/**/*
  needs:
    - build auth-keycloak image
  variables:
    IMAGE_NAME: auth-keycloak
    DOCKER_HUB_REGISTRY_IMAGE: $DOCKER_HUB_REGISTRY_ORG/auth-keycloak
