build auth-keycloak image:
  extends: .docker-build
  variables:
    SERVICE_FOLDER: auth-keycloak
    IMAGE_NAME: auth-keycloak

publish auth-keycloak image:
  extends: .docker-publish
  needs:
    - build auth-keycloak image
  variables:
    IMAGE_NAME: auth-keycloak
    DOCKER_HUB_REGISTRY_IMAGE: $DOCKER_HUB_REGISTRY_ORG/auth-keycloak
