apiVersion: v1
kind: Service
metadata:
  name: {{ template "gateway.fullname" . }}
  labels:
  {{- include "gateway.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http-gateway
      port: {{ .Values.service.port }}
      targetPort: http-gateway
  selector:
  {{- include "gateway.selectorLabels" . | nindent 4 }}
