apiVersion: v2
name: habit
version: 1.0.0
appVersion: v1
description: Chart for the habit service of habitcentric, a service to track habits
keywords:
  - habitcentric
  - habit
  - microservices
home: https://github.com/codecentric/habitcentric/tree/main/services/habit/helm/habit
sources:
  - https://github.com/codecentric/habitcentric
engine: gotpl

dependencies:
  - name: postgresql
    version: 11.9.13
    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
    condition: persistence.deployPostgres
