spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:postgresql:16://localhost/postgres
  jpa:
    properties:
      hibernate:
        format_sql: false
    show-sql: false
