management:
  endpoint:
    chaosmonkey:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,chaosmonkey
chaos:
  monkey:
    watcher:
      rest-controller: true
      controller: true
      repository: true
      service: true
      component: false
    assaults:
      exceptions-active: true
      latency-active: false
