global:
  tag: 1.12.1
  tracer:
    zipkin:
      address: jaeger-collector.istio-system.svc.cluster.local:9411

meshConfig:
  enablePrometheusMerge: true
  enableTracing: true
  defaultConfig:
    tracing:
      sampling: 100

istio_cni:
  enabled: true
