image:
  repository: jaegertracing/jaeger-operator
  tag: 1.20.0
  pullPolicy: IfNotPresent
  imagePullSecrets: []

crd:
  install: true

jaeger:
  # Specifies whether Jaeger instance should be created
  create: false

rbac:
  # Specifies whether RBAC resources should be created
  create: true
  pspEnabled: false
  clusterRole: true

serviceAccount:
  # Specifies whether a ServiceAccount should be created
  create: true