stages:
  - test
  - build
  - build image
  - publish image

services:
  - docker:dind

cache:
  paths:
    - node_modules/
    - .yarn

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HUB_REGISTRY_IMAGE: $DOCKER_HUB_REGISTRY_ORG/ui

unit testing:
  stage: test
  image: node:10.15
  before_script:
    - yarn config set cache-folder .yarn
    - yarn install
  script:
    - yarn run test:unit
    - yarn run lint --no-fix --max-warnings 0

build for production:
  stage: build
  image: node:10.15
  before_script:
    - yarn config set cache-folder .yarn
    - yarn install
  script:
    - yarn run build

build image:
  stage: build image
  image: docker:stable
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

publish image:
  stage: publish image
  image: docker:stable
  script:
    - docker login -u $DOCKER_HUB_REGISTRY_USER -p $DOCKER_HUB_REGISTRY_PASSWORD $DOCKER_HUB_REGISTRY
    - docker build -t $DOCKER_HUB_REGISTRY_IMAGE:latest .
    - docker push $DOCKER_HUB_REGISTRY_IMAGE:latest
  only:
    - master
