unit test ui:
  only:
    changes:
      - ui/**/*
  stage: test
  image: node:10
  before_script:
    - cd ui
    - yarn install
  script:
    - yarn run test:unit --coverage --coverageReporters=cobertura
    - yarn run lint --no-fix --max-warnings 0
  cache:
    key: "${CI_COMMIT_REF_NAME}_ui"
    policy: pull-push
    paths:
      - ui/node_modules/
  artifacts:
    reports:
      cobertura: ui/coverage/cobertura-coverage.xml

build ui:
  only:
    changes:
      - ui/**/*
  needs:
    - unit test ui
  stage: build
  image: node:10
  before_script:
    - cd ui
    - yarn install
  script:
    - yarn run build
  cache:
    key: "${CI_COMMIT_REF_NAME}_ui"
    policy: pull
    paths:
      - node_modules/
      - .yarn

build ui image:
  extends: .docker-build
  variables:
    IMAGE_NAME: ui
    SERVICE_FOLDER: ui
  only:
    changes:
      - ui/**/*
  needs:
    - build ui

publish ui image:
  extends: .docker-publish
  only:
    changes:
      - ui/**/*
  needs:
    - build ui image
  variables:
    IMAGE_NAME: ui
    DOCKER_HUB_REGISTRY_IMAGE: $DOCKER_HUB_REGISTRY_ORG/ui
