version: '3.1'
services:
  ui:
    build: .
    environment:
      HABIT_HOST: http://localhost:8419/
      TRACKING_HOST: http://localhost:8419/
      OIDC_AUTH: enabled
      OIDC_AUTHORITY_HOST: http://localhost:8080/auth/realms/habitcentric/.well-known/openid-configuration
      OIDC_CLIENT_ID: gateway
    depends_on:
      - stubs
    ports:
      - 8171:80
  stubs:
    image: rodolpheche/wiremock:2.20.0-alpine
    command: --verbose
    restart: always
    ports:
      - 8419:8080
    volumes:
      - ./stubs:/home/wiremock
