repositories:
  - name: codecentric
    url: https://codecentric.github.io/helm-charts

environments:
  default:
  istio:
  linkerd:

releases:
  - name: ui
    namespace: hc-ui
    labels:
      service: ui
    chart: ../hc-ui/helm/ui
    values:
      - ./helmfile-templates/ui-values.yaml.gotmpl
    hooks:
      {{- if eq .Environment.Name "istio" }}     
      - events: [ "presync" ]
        command: "sh"
        args: [ "-c", "kubectl create namespace {{`{{ .Release.Namespace }}`}} --dry-run -o yaml | kubectl apply -f -" ]
      - events: [ "presync" ]
        command: "kubectl"
        args: [ "label", "ns", "{{`{{ .Release.Namespace }}`}}", "istio-injection=enabled", "--overwrite" ]
      {{- end }}
      {{- if eq .Environment.Name "linkerd" }}     
      - events: [ "presync" ]
        command: "sh"
        args: [ "-c", "kubectl create namespace {{`{{ .Release.Namespace }}`}} --dry-run -o yaml | kubectl apply -f -" ]
      - events: [ "presync" ]
        command: "kubectl"
        args: [ "annotate", "ns", "{{`{{ .Release.Namespace }}`}}", "linkerd.io/inject=enabled", "--overwrite" ]
      {{- end }}
  - name: habit
    namespace: hc-habit
    labels:
      service: habit
    chart: ../hc-habit/helm/habit
    values:
      - ./helmfile-templates/habit-values.yaml.gotmpl
    hooks:
      {{- if eq .Environment.Name "istio" }}     
      - events: [ "presync" ]
        command: "sh"
        args: [ "-c", "kubectl create namespace {{`{{ .Release.Namespace }}`}} --dry-run -o yaml | kubectl apply -f -" ]
      - events: [ "presync" ]
        command: "kubectl"
        args: [ "label", "ns", "{{`{{ .Release.Namespace }}`}}", "istio-injection=enabled", "--overwrite"]
      {{- end }}
      {{- if eq .Environment.Name "linkerd" }}     
      - events: [ "presync" ]
        command: "sh"
        args: [ "-c", "kubectl create namespace {{`{{ .Release.Namespace }}`}} --dry-run -o yaml | kubectl apply -f -" ]
      - events: [ "presync" ]
        command: "kubectl"
        args: [ "annotate", "ns", "{{`{{ .Release.Namespace }}`}}", "linkerd.io/inject=enabled", "--overwrite" ]
      {{- end }}
  - name: track
    namespace: hc-track
    labels:
      service: track
    chart: ../hc-track/helm/track
    values:
      - ./helmfile-templates/track-values.yaml.gotmpl
    hooks:
      {{- if eq .Environment.Name "istio" }}     
      - events: [ "presync" ]
        command: "sh"
        args: [ "-c", "kubectl create namespace {{`{{ .Release.Namespace }}`}} --dry-run -o yaml | kubectl apply -f -" ]
      - events: [ "presync" ]
        command: "kubectl"
        args: [ "label", "ns", "{{`{{ .Release.Namespace }}`}}", "istio-injection=enabled", "--overwrite" ]
      {{- end }}
      {{- if eq .Environment.Name "linkerd" }}     
      - events: [ "presync" ]
        command: "sh"
        args: [ "-c", "kubectl create namespace {{`{{ .Release.Namespace }}`}} --dry-run -o yaml | kubectl apply -f -" ]
      - events: [ "presync" ]
        command: "kubectl"
        args: [ "annotate", "ns", "{{`{{ .Release.Namespace }}`}}", "linkerd.io/inject=enabled", "--overwrite" ]
      {{- end }}
  - name: report
    namespace: hc-report
    labels:
      service: report
    chart: ../hc-report/helm/report
    values:
      - ./helmfile-templates/report-values.yaml.gotmpl
    hooks:
      {{- if eq .Environment.Name "istio" }}     
      - events: [ "presync" ]
        command: "sh"
        args: [ "-c", "kubectl create namespace {{`{{ .Release.Namespace }}`}} --dry-run -o yaml | kubectl apply -f -" ]
      - events: [ "presync" ]
        command: "kubectl"
        args: [ "label", "ns", "{{`{{ .Release.Namespace }}`}}", "istio-injection=enabled", "--overwrite" ]
      {{- end }}
      {{- if eq .Environment.Name "linkerd" }}     
      - events: [ "presync" ]
        command: "sh"
        args: [ "-c", "kubectl create namespace {{`{{ .Release.Namespace }}`}} --dry-run -o yaml | kubectl apply -f -" ]
      - events: [ "presync" ]
        command: "kubectl"
        args: [ "annotate", "ns", "{{`{{ .Release.Namespace }}`}}", "linkerd.io/inject=enabled", "--overwrite" ]
      {{- end }}
  - name: keycloak
    namespace: hc-keycloak
    labels:
      service: keycloak
    chart: codecentric/keycloak
    version: 8.3.0
    values:
      - ./helmfile-templates/keycloak-values.yaml.gotmpl
    hooks:
      {{- if eq .Environment.Name "istio" }}     
      - events: [ "presync" ]
        command: "sh"
        args: [ "-c", "kubectl create namespace {{`{{ .Release.Namespace }}`}} --dry-run -o yaml | kubectl apply -f -" ]
      - events: [ "presync" ]
        command: "kubectl"
        args: [ "label", "ns", "{{`{{ .Release.Namespace }}`}}", "istio-injection=enabled", "--overwrite" ]
      {{- end }}
      {{- if eq .Environment.Name "linkerd" }}     
      - events: [ "presync" ]
        command: "sh"
        args: [ "-c", "kubectl create namespace {{`{{ .Release.Namespace }}`}} --dry-run -o yaml | kubectl apply -f -" ]
      - events: [ "presync" ]
        command: "kubectl"
        args: [ "annotate", "ns", "{{`{{ .Release.Namespace }}`}}", "linkerd.io/inject=enabled", "--overwrite" ]
      {{- end }}
  {{- if eq .Environment.Name "default" }}
  - name: gateway
    namespace: hc-gateway
    labels:
      service: gateway
    chart: ../hc-gateway/helm/gateway
    values:
      - ./helmfile-templates/gateway-values.yaml.gotmpl
  {{- end }}  
  
