apiVersion: v2
name: track
version: 1.0.0
appVersion: v1
description: Chart for the track service of habitcentric, a service to track habits
keywords:
  - habitcentric
  - track
  - microservices
home: https://github.com/codecentric/habitcentric/tree/main/services/track/helm/track
sources:
  - https://github.com/codecentric/habitcentric
engine: gotpl

dependencies:
  - name: postgresql
    version: 14.3.3
    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
    condition: persistence.deployPostgres
