test habit:
  only:
    changes:
      - habit/**/*
  stage: test
  services:
    - docker:19.03.1-dind@sha256:ffa52c7b48390439f5858cadfaf8163c8cde2104873b3dc9850d8e021dbd3f24
  image: openjdk:11.0.4-jdk-slim-buster@sha256:aa55d9c3be02f2710d5fb5fef87d5c07c9f7ad2c481105a891a4bdd485b2e2bd
  before_script:
    - cd habit
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script: ./gradlew --build-cache check
  cache:
    key: "${CI_COMMIT_REF_NAME}_habit"
    policy: push
    paths:
      - habit/build
      - habit/.gradle
  artifacts:
    when: always
    name: "${CI_BUILD_STAGE}_habit_${CI_BUILD_REF_NAME}"
    expire_in: 1 week
    paths:
      - habit/build/reports/tests/
      - habit/build/test-results/test/TEST-*.xml
      - habit/build/reports/jacoco/test/jacocoTestReport.xml
    reports:
      junit: habit/build/test-results/*/TEST-*.xml

coverage habit:
  only:
    changes:
      - habit/**/*
  stage: test
  needs:
    - test habit
  image: registry.gitlab.com/haynes/jacoco2cobertura:1.0.7
  script:
    # convert report from jacoco to cobertura, using relative project path
    - python /opt/cover2cover.py habit/build/reports/jacoco/test/jacocoTestReport.xml $CI_PROJECT_DIR/habit/src/main/java/ > habit/build/cobertura.xml
  artifacts:
    reports:
      cobertura: habit/build/cobertura.xml

build habit:
  only:
    changes:
      - habit/**/*
  needs:
    - test habit
  stage: build
  image: openjdk:11.0.4-jdk-slim-buster@sha256:aa55d9c3be02f2710d5fb5fef87d5c07c9f7ad2c481105a891a4bdd485b2e2bd
  before_script:
    - cd habit
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script: ./gradlew --build-cache build
  cache:
    key: "${CI_COMMIT_REF_NAME}_habit"
    policy: pull
    paths:
      - habit/build
      - habit/.gradle
  artifacts:
    when: always
    name: "${CI_BUILD_STAGE}_habit_${CI_BUILD_REF_NAME}"
    expire_in: 1 week
    paths:
      - habit/build/libs/hc-habit-*.jar

build habit image:
  only:
    changes:
      - habit/**/*
  needs:
    - build habit
  stage: build image
  image: docker:19.03.1@sha256:5372cccaf84ae9a4d4f5c2b50ba7db6627cf3eff12785876f3354bbc2b0b57ea
  services:
    - docker:19.03.1-dind@sha256:ffa52c7b48390439f5858cadfaf8163c8cde2104873b3dc9850d8e021dbd3f24
  before_script:
    - cd habit
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

publish habit image:
  only:
    refs:
      - main
    changes:
      - habit/**/*
  needs:
    - build habit image
  variables:
    DOCKER_HUB_REGISTRY_IMAGE: $DOCKER_HUB_REGISTRY_ORG/habit
  stage: publish image
  image: docker:19.03.1@sha256:5372cccaf84ae9a4d4f5c2b50ba7db6627cf3eff12785876f3354bbc2b0b57ea
  services:
    - docker:19.03.1-dind@sha256:ffa52c7b48390439f5858cadfaf8163c8cde2104873b3dc9850d8e021dbd3f24
  before_script:
    - cd habit
  script:
    - docker login -u $DOCKER_HUB_REGISTRY_USER -p $DOCKER_HUB_REGISTRY_PASSWORD $DOCKER_HUB_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG $DOCKER_HUB_REGISTRY_IMAGE:latest
    - docker push $DOCKER_HUB_REGISTRY_IMAGE:latest
