version: '3.1'
services:
  app:
    build: .
    environment:
      DB_HOST: db
    ports:
      - 8180:8080
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./src/test/resources/db:/docker-entrypoint-initdb.d
  adminer:
    image: adminer
    restart: always
    ports:
      - 8380:8080
    depends_on:
      - db
