name: gateway service

on:
  push:
    branches:
      - '**'
    paths:
      - .github/workflows/build-java-service.yaml
      - .github/workflows/parse-junit-results.yaml
      - .github/workflows/gateway.yaml
      - services/gateway

jobs:
  build:
    uses: ./.github/workflows/build-java-service.yaml
    with:
      service_name: gateway

  docker:
    uses: ./.github/workflows/build-docker.yaml
    needs: build
    with:
      image-name: gateway
      working-dir: ./services/gateway
      artifact-name: ${{ needs.build.outputs.artifact-name }}
      artifact-path: ${{ needs.build.outputs.artifact-path }}
