name: gateway service

on:
  push:
    branches:
      - '**'
    paths:
      - .github/workflows/prepare-release.yaml
      - .github/workflows/build-java-service.yaml
      - .github/workflows/parse-junit-results.yaml
      - .github/workflows/build-docker.yaml
      - .github/workflows/release.yaml
      - .github/workflows/gateway.yaml
      - services/gateway/**

jobs:
  prepare-release:
    uses: ./.github/workflows/prepare-release.yaml
    with:
      working-dir: ./services/gateway

  build:
    uses: ./.github/workflows/build-java-service.yaml
    needs: prepare-release
    with:
      service_name: gateway
      version: ${{ needs.prepare-release.outputs.release-version }}

  docker:
    uses: ./.github/workflows/build-docker.yaml
    needs:
      - prepare-release
      - build
    with:
      image-name: gateway
      working-dir: ./services/gateway
      version: ${{ needs.prepare-release.outputs.release-version }}
      artifact-name: ${{ needs.build.outputs.jar-artifact-name }}
      artifact-path: ${{ needs.build.outputs.jar-artifact-path }}

  github-release:
    uses: ./.github/workflows/release.yaml
    needs:
      - prepare-release
      - build
      - docker
    with:
      service-name: gateway
      version: ${{ needs.prepare-release.outputs.release-version }}
      change-notes: ${{ needs.prepare-release.outputs.release-notes }}
      license-artifact-name: ${{ needs.build.outputs.license-artifact-name }}
      license-artifact-path: ${{ needs.build.outputs.license-artifact-path }}
