name: 'JUnit test results'

on:
  workflow_run:
    workflows:
      - habit service
    types:
      - completed

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: 📋 Parse test results
        uses: dorny/test-reporter@v1
        with:
          artifact: test-results
          name: Test results
          path: '**/TEST-*.xml'
          reporter: java-junit
