name: report service

on:
  push:
    branches:
      - '**'
    paths:
      - .github/workflows/build-java-service.yaml
      - .github/workflows/parse-junit-results.yaml
      - .github/workflows/report.yaml
      - services/report

jobs:
  habit:
    uses: ./.github/workflows/build-java-service.yaml
    with:
      service_name: report
