name: report service

on:
  push:
    branches:
      - '**'
    paths:
      - .github/workflows/build-java-service.yaml
      - .github/workflows/parse-junit-results.yaml
      - .github/workflows/report.yaml
      - services/report

jobs:
  build:
    uses: ./.github/workflows/build-java-service.yaml
    with:
      service_name: report

  docker:
    uses: ./.github/workflows/build-docker.yaml
    needs: build
    with:
      image-name: report
      working-dir: ./services/report
      artifact-name: ${{ needs.build.outputs.artifact-name }}
      artifact-path: ${{ needs.build.outputs.artifact-path }}
