name: track service

on:
  push:
    branches:
      - '**'
    paths:
      - .github/workflows/build-java-service.yaml
      - .github/workflows/parse-junit-results.yaml
      - .github/workflows/track.yaml
      - services/track

jobs:
  build:
    uses: ./.github/workflows/build-java-service.yaml
    with:
      service_name: track

  docker:
    uses: ./.github/workflows/build-docker.yaml
    needs: build
    with:
      image-name: track
      working-dir: ./services/track
      artifact-name: ${{ needs.build.outputs.artifact-name }}
      artifact-path: ${{ needs.build.outputs.artifact-path }}
