name: track service

on:
  push:
    branches:
      - '**'
    paths:
      - .github/workflows/build-java-service.yaml
      - .github/workflows/parse-junit-results.yaml
      - .github/workflows/track.yaml
      - services/track

jobs:
  habit:
    uses: ./.github/workflows/build-java-service.yaml
    with:
      service_name: track
